
server:
  port: 9090
  tomcat:
    remoteip:
      trusted-proxies: ".*"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/*sql
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_SCHEMA:postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  application:
    name: authorization-service
