name: Deploy

env:

  GCLOUD_SA_KEY:  ${{ secrets.GCLOUD_SA_KEY }}
  GCLOUD_PROJECT: joshlong
  GH_PAT: ${{ secrets.MOGUL_GITHUB_PERSONAL_ACCESS_TOKEN }}

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build Container
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker us-docker.pkg.dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish Container
        run: |
          cd $GITHUB_WORKSPACE
          APP_NAME=mogul-service
          IMAGE_NAME=us-docker.pkg.dev/${GCLOUD_PROJECT}/mogul-artifact-registry/${APP_NAME}:latest
          echo "the image name is $IMAGE_NAME "
          ./mvnw -DskipTests=true spring-javaformat:apply clean package spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Invoke Pipeline
        run : |
          curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${GH_PAT}" --request POST  --data '{"event_type": "update-event"}' https://api.github.com/repos/bootiful-media-mogul/pipeline/dispatches
          echo "Invoking the pipeline to have it deploy everything..." 

